window.PRINT_CASE_MODELS = {
  "Apple": [
    "iPhone 7/8/SE3",
    "iPhone 7/8 Plus",
    "iPhone XR",
    "iPhone XS",
    "iPhone XS Max",
    "iPhone 11",
    "iPhone 11 Pro",
    "iPhone 11 Pro Max",
    "iPhone 12",
    "iPhone 12 MagSafe",
    "iPhone 12 mini",
    "iPhone 12 mini MagSafe",
    "iPhone 12 Pro",
    "iPhone 12 Pro MagSafe",
    "iPhone 12 Pro Max",
    "iPhone 12 Pro Max MagSafe",
    "iPhone 13",
    "iPhone 13 MagSafe",
    "iPhone 13 mini",
    "iPhone 13 mini MagSafe",
    "iPhone 13 Pro",
    "iPhone 13 Pro MagSafe",
    "iPhone 13 Pro Max",
    "iPhone 13 Pro Max MagSafe",
    "iPhone 14",
    "iPhone 14 MagSafe",
    "iPhone 14 Pro",
    "iPhone 14 Pro MagSafe",
    "iPhone 14 Plus",
    "iPhone 14 Plus MagSafe",
    "iPhone 14 Pro Max",
    "iPhone 14 Pro Max MagSafe",
    "iPhone 15",
    "iPhone 15 MagSafe",
    "iPhone 15 Pro",
    "iPhone 15 Pro MagSafe",
    "iPhone 15 Plus",
    "iPhone 15 Plus MagSafe",
    "iPhone 15 Pro Max",
    "iPhone 15 Pro Max MagSafe",
    "iPhone 16",
    "iPhone 16 MagSafe",
    "iPhone 16 Pro",
    "iPhone 16 Pro MagSafe",
    "iPhone 16 Plus",
    "iPhone 16 Plus MagSafe",
    "iPhone 16 Pro Max",
    "iPhone 16 Pro Max MagSafe",
    "iPhone 16e/17e",
    "iPhone 16e/17e MagSafe",
    "iPhone 17",
    "iPhone 17 MagSafe",
    "iPhone 17 Pro",
    "iPhone 17 Pro MagSafe",
    "iPhone 17 Air",
    "iPhone 17 Air MagSafe",
    "iPhone 17 Pro Max"
    "iPhone 17 Pro Max MagSafe",
  ],
  "Samsung": [
    "Galaxy S21",
    "Galaxy S21+",
    "Galaxy S21 Ultra",
    "Galaxy S22",
    "Galaxy S22 Magnetic",
    "Galaxy S22+",
    "Galaxy S22+ Magnetic",
    "Galaxy S22 Ultra",
    "Galaxy S22 Ultra Magnetic",
    "Galaxy S23",
    "Galaxy S23 Magnetic",
    "Galaxy S23+",
    "Galaxy S23+ Magnetic",
    "Galaxy S23 Ultra",
    "Galaxy S23 Ultra Magnetic",
    "Galaxy S24",
    "Galaxy S24 Magnetic",
    "Galaxy S24+",
    "Galaxy S24+ Magnetic",
    "Galaxy S24 Ultra",
    "Galaxy S24 Ultra Magnetic",
    "Galaxy S25",
    "Galaxy S25 Magnetic",
    "Galaxy S25+",
    "Galaxy S25+ Magnetic",
    "Galaxy S25 Ultra",
    "Galaxy S25 Ultra Magnetic",
    "Galaxy A56",
    "Galaxy A55",
    "Galaxy A54",
    "Galaxy A53",
    "Galaxy A52",
    "Galaxy A36",
    "Galaxy A35",
    "Galaxy A34",
    "Galaxy A26",
    "Galaxy A25",
    "Galaxy A23",
    "Galaxy A17",
    "Galaxy A16",
    "Galaxy A15",
    "Galaxy A14",
    "Galaxy A07",
    "Galaxy A06",
    "Galaxy A05",
    "Galaxy A05S",
    "Galaxy S23 FE",
    "Galaxy S24 FE",
    "Galaxy S25 FE",
  ],
  "Google": [
    "Pixel 8",
    "Pixel 8 Pro",
    "Pixel 9/9 Pro",
    "Pixel 9 Pro XL",
    "Pixel 9A",
    "Pixel 10/10 Pro",
    "Pixel 10 Pro XL"
  ],
  "Xiaomi": [
    "Xiaomi 12",
    "Xiaomi 12 Pro",
    "Xiaomi 13",
    "Xiaomi 14T",
    "Xiaomi 17",
    "Redmi K60/K60 Pro",
    "Redmi K70/K70 Pro",
    "Redmi K70 Ultra",
    "Redmi Note 12 4G",
    "Xiaomi POCO X7 Pro 5G",
    "Redmi Note 12 Pro 4G",
    "Redmi Note 12 Pro+",
    "Redmi Note 14 4G",
  ],
  "OPPO": [
    "Reno14 Pro 5G",
    "A60 4G",
    "A3 Pro 5G",
    "A3 4G",
    "A3X 5G"
  ],
};
